### ISSUE TITLE
Reproduce the results on the paper 

### ISSUE THREAD

**Issue by ghost** [YantaoShen/kpm_rw_person_reid#4]
I followed all the instruction you have given above, and the model does converge, but the final precision is not the same with what is reported on the paper. Also, the model was not affected when I remove the random walk computation. Do you have any comment on this?

Thanks

**Comment by YantaoShen** [comment]
Could you provide the command you used and logs?

**Comment by YantaoShen** [comment]
Since no more comments are provided after a month, I will close the issue.
