### ISSUE TITLE
final model files have been broken!

### ISSUE THREAD

**Issue by yonger001** [YantaoShen/kpm_rw_person_reid#5]
Hi, thank you for your work!
The model files you provided have an error during decompression.It shows that the files are corrupted.Waiting for your relp! thanks very much!

**Comment by bigtreeshen** [comment]
could you tell me which one is broken?

**Comment by YantaoShen** [comment]
> Hi, thank you for your work!
> The model files you provided have an error during decompression.It shows that the files are corrupted.Waiting for your relp! thanks very much!

Which one is broken?

**Comment by YantaoShen** [comment]
The '.pth.tar' files do not need to be decompressed. Please check the using of PyTorch pretrained model.

**Comment by yonger001** [comment]
OK，Thank you！
