### ISSUE TITLE
how to run test code with cpu?

### ISSUE THREAD

**Issue by mitrasafari** [YantaoShen/kpm_rw_person_reid#8]
@YantaoShen hello, I install pythorch for cpu version but when I test your code I get error:'AssertionError: Torch not compiled with CUDA enabled' 
can you help me , how I can run code with CPU ?

**Comment by YantaoShen** [comment]
Please try to refer to Pytorch's official guideline of using CPU. Considering the large computation requirement, we highly recommend you to run the code on the GPU platform.
